
modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/defeatedcrow/HarvestWithDispenser/issues/"
license="All Rights Reserved, see ReadMe (https://github.com/defeatedcrow/HarvestWithDispenser)"

[[mods]]
modId="dcs_dispenser"
version="3.0.1"
displayName="HarvestWithDispenser"
displayURL="https://defeatedcrow.jp/modwiki/HarvestWithDispenser/"
logoFile="harvest_with_dispenser_200.png"
credits="defeatedcrow"
authors="defeatedcrow"
description=""

[[dependencies.dcs_dispenser]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.dcs_dispenser]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="SERVER"
